### ISSUE TITLE
[Bug] Node.js `~/local/opt/node-v{version}/` directory has wrong permissions

### ISSUE THREAD

**Issue by jojobyte** [webinstall/webi-installers#526] opened 2022-10-13 22:22 UTC
## What were you trying to install (or what else went wrong)?

node

https://user-images.githubusercontent.com/184880/195721733-fe1abd11-8213-4bb7-b1a9-b4c201614a9e.mp4

## What exactly did you do?

Ran `curl -sS https://webi.sh/node | sh` and `webi node@16`

## What went wrong?

`~/local/opt/node-v{version}/` has permissions of user & group `1001:1001`

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux (Ubuntu 22.04)

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [x] Other (Digital Ocean Droplet)

**Comment by coolaj86** [comment] 2022-10-13 22:27
I just tried and I can't reproduce.

```txt
webi node@16

Downloading node from
https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.gz

Saved as /home/app/Downloads/webi/node/16.18.0/node-v16.18.0-linux-x64.tar.gz
Extracting /home/app/Downloads/webi/node/16.18.0/node-v16.18.0-linux-x64.tar.gz
Installing to /home/app/.local/opt/node-v16.18.0/bin/node
Installed 'node' and 'npm' at /home/app/.local/opt/node
```

```txt
app@beta:~$ ls -lAhF ~/.local/opt/node-v16.18.0/
total 820K
-rw-r--r-- 1 app app 677K Oct 12 12:00 CHANGELOG.md
-rw-r--r-- 1 app app  87K Oct 12 12:00 LICENSE
-rw-r--r-- 1 app app  35K Oct 12 12:00 README.md
drwxr-xr-x 2 app app 4.0K Oct 12 12:00 bin/
drwxr-xr-x 3 app app 4.0K Oct 12 12:00 include/
drwxr-xr-x 3 app app 4.0K Oct 12 12:00 lib/
drwxr-xr-x 4 app app 4.0K Oct 12 12:00 share/
```

What type of linux are you using?

```sh
cat /etc/issue
````

**Comment by coolaj86** [comment] 2022-10-13 22:30
What type of linux are you using?

```sh
cat /etc/issue
````

What was user id 1001 on your system? Do you perhaps delete a user and add it back with the same name?

Do `/etc/password` or `/etc/group` have any anomolies?

**Comment by jojobyte** [comment] 2022-10-13 22:31
`doctl compute d c --image ubuntu-22-04-x64`

**Comment by coolaj86** [comment] 2022-10-13 22:36
With rare, rare exception: **don't use `webi` as `root`!**

Webi is desired to be secure and won't work in insecure environments.

You're getting the wrong UIDs because you're running as root and the root user will copy IDs from an extracted tarball rather than setting it to the current user id.

Create an `app` user and run your applications under that user.

Try this:

```sh
ssh root@<ip> "curl https://webi.sh/ssh-adduser | sh"
ssh app@<ip>
```

You can use https://webinstall.dev/serviceman/ and https://webinstall.dev/setcap-netbind/ to run services under the user rather than as root.

**Comment by jojobyte** [comment] 2022-10-13 22:38
This is not just a root user issue, the first place I noticed this was on that new desktop which had a normal user created in the setup process, it had the exact same issue

**Comment by coolaj86** [comment] 2022-10-13 22:39
Reproduce it and _maybe_ I'll believe it.

Standard users don't have permission to create files belonging to another user.

**Comment by coolaj86** [comment] 2022-10-13 22:50
See <https://youtu.be/4lp-wm5S4Dw> and <https://youtu.be/YH5gOderlMI>.

Closing because the error was definitely the use of `sudo` or `root`.

**Closed by coolaj86** 2022-10-13 22:50 UTC
Labels: bug

**Comment by jojobyte** [comment] 2022-10-13 23:08
If I get to the point where I decide to re-install the os on that computer again I'll try to record the setup, right now it won't reproduce, but I've looked at the `.bash_history` and it definately did not use sudo to install `webi` or `webi node`

```sh
# .bash_history
curl -sS https://webi.sh/ | sh
source ~/.config/envman/PATH.env
webi node
source ~/.config/envman/PATH.env
node -v
webi deno
curl -sS https://webi.sh/deno | sh
webi golang
webi go-essentials
source ~/.config/envman/PATH.env
go version
webi vim-essentials
webi vim-devicons
webi vim-nerdtree
webi vim-go
webi rustlang
source ~/.config/envman/PATH.env
rustc -V
webi zig
source ~/.config/envman/PATH.env
zig -h
node -v
webi vim-rust
webi jshint
```
