### ISSUE TITLE
[Installer] Add Zsh

### ISSUE THREAD

**Issue by NightMachinery** [webinstall/webi-installers#603] opened 2023-05-17 19:51 UTC

**Comment by coolaj86** [comment] 2023-06-01 06:23
The problem with zsh is that there's no official builds: https://www.zsh.org/

I can't even find unofficial builds.

It's pretty much package repo or bust.

One of the goals of webi is to be for _modern_ software that can be safely installed in the user's home directory without creating conflict with system libs or bins.

**I'm willing to entertain zsh**, but someone else will have to do some legwork to figure out how to get builds that are as close to "official" as possible, and that are (probably) statically compiled so that they don't conflict with system libs, etc.

Closing for now.

**Closed by coolaj86** 2023-06-01 06:23 UTC
Labels: good first issue, first-timers-only, up-for-grabs

**Comment by NightMachinery** [comment] 2023-06-01 19:49
@coolaj86 [brew](https://formulae.brew.sh/formula/zsh) installs zsh in my home directory, though it seems to build it from source.

**Comment by coolaj86** [comment] 2023-06-06 17:24
Yes, if you use Webi to install `brew` (or follow the official instructions to have brew install to your home director like Webi does), then it will install `zsh` (and everything else) safely in your home directory.

However, it _must_ compile from source every time - because it's not configured for static build like modern software is, and the configuration flags aren't updated for relative paths like modern software is, so it hard codes your username as part of the paths for the build (ex: `/home/me/...`) - so what works on your machine _only_ works on your machine.

If zsh were to be updated to handle the modern approach then we would actually be able to use brew bottles as an install source and have a conflict-free installer from brew bottles.

A lot of projects don't see the value in the modern approach (they come from the old days where conserving disk space was really important, and reproducible build and environments weren't really a thing), or they don't have the resources to figure out the modern build processes, or they believe that a software developer's job ends where a package distributor's job begins (like the old day). And we don't have the resources to figure all of that out for each project (especially because we eschew dangerous languages like C and C++ and the related `automake` tool chains in favor of investing in learning modern, safe, reproducible alternatives.

**Comment by coolaj86** [comment] 2023-06-06 17:35
If it were up to me all software would have to ship with a similar warning to all prepared foods and manufactured products sold in the US:

> C99 WARNING: This software can expose your computer to memory unsafe code including C, which is known to the state of California to cause viruses, crashes and data loss, or other productive harm.

(if you don't get the reference: https://brownslandfarm.com/pages/p65-warning-state-of-california)
