### ISSUE TITLE
[Bug] BAT Install results in a non-working BAT (GLIBC)

### ISSUE THREAD

**Issue by cawoodm** [webinstall/webi-installers#296] opened 2021-08-30 08:26 UTC
## What were you trying to install (or what else went wrong)?
Installed `bat` but it fails to run:
![image](https://user-images.githubusercontent.com/498834/131309133-15d98d6e-9ac8-4475-8bd7-e490bb5664f3.png)

## What exactly did you do?

```bash
 webi bat

Thanks for using webi to install 'bat' on 'linux/amd64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Downloading bat from
https://github.com/sharkdp/bat/releases/download/v0.18.3/bat-v0.18.3-x86_64-unknown-linux-gnu.tar.gz

Saved as /home/***/Downloads/bat-v0.18.3-x86_64-unknown-linux-gnu.tar.gz
Extracting /home/***/Downloads/bat-v0.18.3-x86_64-unknown-linux-gnu.tar.gz
Installing to /home/***/.local/opt/bat-v0.18.3/bin/bat
Installed 'bat' v0.18.3 as /home/u29730/.local/bin/bat
```

## What went wrong?
```bash
[~]$ bat /etc/rancher/k3s/k3s.yaml
bat: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by bat)
```

## Which OS did you try on?

`CentOS Linux release 7.9.2009 (Core)` - works on Ubuntu, just not (my) CentOS.

- [ ] Mac
- [ ] Windows
- [X] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment] 2021-08-30 18:20
Confirmed.

It should be downloading `bat-v0.18.3-i686-unknown-linux-musl.tar.gz` instead. `musl` is statically compiled, distro independent.

I think the quick fix will be to do the same here as we do for the Apple M1 - try to download a version that matches the string `musl` and then fall back to a non-matching version.

Ideally I'd like some way to rank listings such that if there's a particular match it ranks higher, but if a probably-compatible match is found it still ranks (which will be required for Windows ARM soon as well).

**Comment by coolaj86** [comment] 2021-09-10 20:19
I should be able to make time to fix this tomorrow (Saturday). Commenting such to help with my resolve and commitment. :)

**Comment by coolaj86** [comment] 2021-11-23 11:07
I'm closing this because I think I've fixed it.

That said, @cawoodm will you test and see if it's working for you now?

```bash
webi bat
```

**Closed by coolaj86** 2021-11-23 11:07 UTC
Labels: bug
