### ISSUE TITLE
[SOLVED] The curious case of Schrödinger's File...

### ISSUE THREAD

**Issue by tomcam** [webinstall/webi-installers#300] opened 2021-09-22 22:03 UTC
## What were you trying to install (or what else went wrong)?

webi

## What exactly did you do?

Per instructions at https://webinstall.dev/ I logged into My Windows 10

- Logged into my Windows 10 home machine 
- Copied the curl line from the home page `curl.exe -A "MS" https://webinstall.dev/webi | powershell`
- Open PowerShell as admin
- Pasted in the line

## What went wrong?

Seems to be missing an executable? Here's the output.

```
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> # Download the latest webi, then install webi
PS C:\Windows\system32> New-Item -Path .local\bin -ItemType Directory -Force | out-null
PS C:\Windows\system32> IF ($Env:WEBI_HOST -eq $null -or $Env:WEBI_HOST -eq "") { $Env:WEBI_HOST = "https://webinstall.dev"}
PS C:\Windows\system32> curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
PS C:\Windows\system32> Set-ExecutionPolicy -Scope Process Bypass
PS C:\Windows\system32> & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "webi"
& : The term 'C:\Users\tomca\.local\bin\webi-pwsh.ps1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:3
+ & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "webi"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\tomca\.local\bin\webi-pwsh.ps1:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

```
## Which OS did you try on?

- [ ] Mac
- [ X] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)
- [ ] 

LG Gram laptop, 11th Gen i5-1135G7 @ 2.40Ghz, 16GB RAM running Windows 10 Home 20H2, 1TB drive with 300GB free

**Comment by tomcam** [comment] 2021-09-22 22:04
Sorry, somehow saved without finishing. Rig:

LG Gram laptop, 11th Gen i5-1135G7 @ 2.40Ghz, 16GB RAM running Windows 10 Home 20H2, 1TB drive with 300GB free

**Comment by coolaj86** [comment] 2021-09-23 03:02
Would you mind checking a few things for me?

What's the output of this?

```cmd
pushd C:\Users\tomca\.local\bin\webi-pwsh.ps1
dir
type webi-pwsh.ps1
```

Does it work if you run it from cmd.exe rather than PowerShell?

Does it work if you reboot?

Someone else had this problem the other day, but I haven't been able to replicate it yet.

**Comment by coolaj86** [comment] 2021-09-23 03:04
From the output I can see that this was successful:

```pwsh
curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
```

And I can see that this fails:

```pwsh
& "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "webi"
```

Well hello _Schrödinger's File_... that's an impossible condition.

Since the file obviously can't both exist and _not_ exist simultaneously, the error message must be wrong. Hmm... 🧐

**Comment by coolaj86** [comment] 2021-11-23 09:34
# Solved

> Open PowerShell as admin

I missed the significance of that line before.

**You should NOT run Webi in an elevated console**. Webi is safe and secure, and expected to be run as the logged in user **without admin privileges**.

When you run this as admin, it changes some of the environment variables - hence the file does in fact both exist, and not exist at the same time. It _was_ downloaded to the correct place, but then it's being read from the wrong place (perhaps system32 or the built-in admin USERPROFILE).

I'm closing this out because I was able to reproduce the problem and confirm that running as admin gives me the same error. If you still have any problems, let me know.

**Closed** 2021-11-23 09:35 UTC
Labels: bug

**Comment by coolaj86** [comment] 2021-11-23 09:41
P.S. @tomcam can you confirm?

**Comment by ajeetdsouza** [comment] 2021-11-23 09:54
Is there a way we can detect this and return a better error?
