### ISSUE TITLE
problem with yq installer

### ISSUE THREAD

**Issue by liudonghua123** [webinstall/webi-installers#313] opened 2021-11-08 08:22 UTC
When I tried to install `yq`, I saw the following error logs.

```
Install Location: C:\Users\Liu.D.H\.local\opt\yq-v4.14.1\bin\yq.exe
Move-Item : Cannot find path 'C:\Users\Liu.D.H\.local\tmp\yq.exe' because it does not exist.
At C:\Users\Liu.D.H\.local\tmp\yq.install.ps1:77 char:9
+         Move-Item -Path ".\yq.exe" -Destination "$pkg_src_bin"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Liu.D.H\.local\tmp\yq.exe:String) [Move-Item], ItemNotFoundExc
   eption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

PS C:\Users\Liu.D.H>
```

And I checked the binary filename is not `yq.exe` but `yq_windows_amd64.exe` in `yq_windows_amd64.zip`.

**Comment by ajeetdsouza** [comment] 2021-11-08 14:41
This appears to be a duplicate of https://github.com/webinstall/webi-installers/issues/307.

**Comment by coolaj86** [comment] 2021-11-15 12:07
Hey @liudonghua123 @ajeetdsouza,

I've got a PR up for the fix. Could either of you test on Windows?

```bash
curl.exe -fsSL https://beta.webinstall.dev/yq | powershell
```

**Comment by liudonghua123** [comment] 2021-11-16 01:43
I tried, it seemed still not work.

```shell
C:\Users\Liu.D.H\Downloads\webi>curl.exe -A "MS" https://beta.webinstall.dev/yq | powershell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

100   425    0   425    0     0    425      0 --:--:--  0:00:01 --:--:--   305
# Download the latest webi, then install yq
PS C:\Users\Liu.D.H\Downloads\webi> New-Item -Path .local\bin -ItemType Directory -Force | out-null
PS C:\Users\Liu.D.H\Downloads\webi> IF ($Env:WEBI_HOST -eq $null -or $Env:WEBI_HOST -eq "") { $Env:WEBI_HOST = "https://beta.webinstall.dev"}
PS C:\Users\Liu.D.H\Downloads\webi> curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
PS C:\Users\Liu.D.H\Downloads\webi> Set-ExecutionPolicy -Scope Process Bypass
PS C:\Users\Liu.D.H\Downloads\webi> & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "yq"
PATH not changed.

Downloading https://beta.webinstall.dev/api/installers/yq.ps1?formats=zip,exe,tar
PATH not changed.

Installing yq
Unpacking C:\Users\Liu.D.H\Downloads\webi\yq_windows_amd64.zip
Install Location: C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe
Copying into 'C:\Users\Liu.D.H\.local\bin\yq.exe' from 'C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe'
Copy-Item : Cannot find path 'C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe' because it does not exist.
At C:\Users\Liu.D.H\.local\tmp\yq.install.ps1:89 char:1
+ Copy-Item -Path "$pkg_src" -Destination "$pkg_dst" -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Liu.D....14.2\bin\yq.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

PS C:\Users\Liu.D.H\Downloads\webi>
C:\Users\Liu.D.H\Downloads\webi>curl.exe -A "MS" https://beta.webinstall.dev/webi | powershell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

100   429    0   429    0     0    429      0 --:--:-- --:--:-- --:--:--   435
# Download the latest webi, then install webi
PS C:\Users\Liu.D.H\Downloads\webi> New-Item -Path .local\bin -ItemType Directory -Force | out-null
PS C:\Users\Liu.D.H\Downloads\webi> IF ($Env:WEBI_HOST -eq $null -or $Env:WEBI_HOST -eq "") { $Env:WEBI_HOST = "https://beta.webinstall.dev"}
PS C:\Users\Liu.D.H\Downloads\webi> curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
PS C:\Users\Liu.D.H\Downloads\webi> Set-ExecutionPolicy -Scope Process Bypass
PS C:\Users\Liu.D.H\Downloads\webi> & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "webi"
PATH not changed.

Downloading https://beta.webinstall.dev/api/installers/webi.ps1?formats=zip,exe,tar
PATH not changed.

PS C:\Users\Liu.D.H\Downloads\webi>
C:\Users\Liu.D.H\Downloads\webi>curl.exe -A "MS" https://beta.webinstall.dev/yq | powershell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

100   425    0   425    0     0    425      0 --:--:--  0:00:01 --:--:--   425
# Download the latest webi, then install yq
PS C:\Users\Liu.D.H\Downloads\webi> New-Item -Path .local\bin -ItemType Directory -Force | out-null
PS C:\Users\Liu.D.H\Downloads\webi> IF ($Env:WEBI_HOST -eq $null -or $Env:WEBI_HOST -eq "") { $Env:WEBI_HOST = "https://beta.webinstall.dev"}
PS C:\Users\Liu.D.H\Downloads\webi> curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
PS C:\Users\Liu.D.H\Downloads\webi> Set-ExecutionPolicy -Scope Process Bypass
PS C:\Users\Liu.D.H\Downloads\webi> & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "yq"
PATH not changed.

Downloading https://beta.webinstall.dev/api/installers/yq.ps1?formats=zip,exe,tar
PATH not changed.

Installing yq
Unpacking C:\Users\Liu.D.H\Downloads\webi\yq_windows_amd64.zip
Install Location: C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe
Move-Item : Cannot create a file when that file already exists.
At C:\Users\Liu.D.H\.local\tmp\yq.install.ps1:82 char:9
+         Move-Item -Path ".\yq*.exe" -Destination "$pkg_src_bin"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Liu.D....ndows_amd64.exe:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

PS C:\Users\Liu.D.H\Downloads\webi>
C:\Users\Liu.D.H\Downloads\webi>
```

I tried to remove `%USERPROFILE%\.local\opt\yq-v4.14.2` and `%USERPROFILE%\.local\tmp` and tried again.

```shell
C:\Users\Liu.D.H>curl.exe -A "MS" https://beta.webinstall.dev/yq | powershell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

100   425    0   425    0     0    425      0 --:--:--  0:00:01 --:--:--   344
# Download the latest webi, then install yq
PS C:\Users\Liu.D.H> New-Item -Path .local\bin -ItemType Directory -Force | out-null
PS C:\Users\Liu.D.H> IF ($Env:WEBI_HOST -eq $null -or $Env:WEBI_HOST -eq "") { $Env:WEBI_HOST = "https://beta.webinstall.dev"}
PS C:\Users\Liu.D.H> curl.exe -s -A "windows" "$Env:WEBI_HOST/packages/_webi/webi-pwsh.ps1" -o "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1"
PS C:\Users\Liu.D.H> Set-ExecutionPolicy -Scope Process Bypass
PS C:\Users\Liu.D.H> & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "yq"
PATH not changed.

Downloading https://beta.webinstall.dev/api/installers/yq.ps1?formats=zip,exe,tar
PATH not changed.

Installing yq
Unpacking C:\Users\Liu.D.H\Downloads\webi\yq_windows_amd64.zip
Install Location: C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe
Copying into 'C:\Users\Liu.D.H\.local\bin\yq.exe' from 'C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe'
Copy-Item : Cannot find path 'C:\Users\Liu.D.H\.local\opt\yq-v4.14.2\bin\yq.exe' because it does not exist.
At C:\Users\Liu.D.H\.local\tmp\yq.install.ps1:89 char:1
+ Copy-Item -Path "$pkg_src" -Destination "$pkg_dst" -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Liu.D....14.2\bin\yq.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

PS C:\Users\Liu.D.H>
C:\Users\Liu.D.H>
```

**Comment by liudonghua123** [comment] 2021-11-17 04:38
I have modified the code to fix this issue.

**Closed** 2021-11-21 03:25 UTC
Labels: bug

**Comment by denzelbrown** [comment] 2021-12-13 23:27
So what's the fix? I'm having the same issue.

**Comment by coolaj86** [comment] 2021-12-13 23:50
@denzelbrown It was fixed in a PR and merged a few weeks ago.

Can you copy and paste the command you ran and the output you get?
