### ISSUE TITLE
Installer for deno

### ISSUE THREAD

**Issue by makuzaverite** [webinstall/webi-installers#229] opened 2021-04-22 16:15 UTC
I'm installing deno on my linux machines using webi but the installer doesn't work

![image](https://user-images.githubusercontent.com/53856673/115748725-b8748d00-a396-11eb-9e89-be8479112afb.png)

**Comment by coolaj86** [comment] 2021-04-22 18:15
Hmmm... they may have changed the naming scheme of their releases. I’ll have to check.

**Comment by coolaj86** [comment] 2021-04-22 18:17
Naming looks good

https://github.com/denoland/deno

I’ll have to investigate...

**Comment by coolaj86** [comment] 2021-04-26 05:24
@makuzaverite I think the problem is that you don't have `unzip` installed.

> no 'deno' release for 'linux' on 'amd64' as one of 1tar,exe,xz,git,dmg' by the tag ''

> `deno` is available for `macos,windows,linux' on 'arm64,amd64' as one of 'zip,tar'.

All of the deno releases are only available in `zip`, which is unusual for linux:

https://webinstall.dev/api/releases/deno@.tab?os=linux&arch=amd64

```tsv
1.9.2	-	stable	2021-04-23	linux	amd64	zip	-	https://github.com/denoland/deno/releases/download/v1.9.2/deno-x86_64-unknown-linux-gnu.zip	
1.9.1	-	stable	2021-04-21	linux	amd64	zip	-	https://github.com/denoland/deno/releases/download/v1.9.1/deno-x86_64-unknown-linux-gnu.zip	
1.9.0	-	stable	2021-04-13	linux	amd64	zip	-	https://github.com/denoland/deno/releases/download/v1.9.0/deno-x86_64-unknown-linux-gnu.zip	
1.8.3	-	stable	2021-04-02	linux	amd64	zip	-	https://github.com/denoland/deno/releases/download/v1.8.3/deno-x86_64-unknown-linux-gnu.zip	
1.8.2	-	stable	2021-03-21	linux	amd64	zip	-	https://github.com/denoland/deno/releases/download/v1.8.2/deno-x86_64-unknown-linux-gnu.zip	
```

I'll close this out, but if you have a suggestion on how to make the error message more clear, I'm open to a PR for that.

**Closed by coolaj86** 2021-04-26 05:24 UTC
