### ISSUE TITLE
[Bug] carriage return error on python install on WSL

### ISSUE THREAD

**Issue by avila-m-6** [webinstall/webi-installers#517] opened 2022-09-15 22:55 UTC
## What were you trying to install (or what else went wrong)?

python

## What exactly did you do?

I ran `curl -sS https://webi.sh/python | sh` as stated in [https://webinstall.dev/python/]()

I then removed it and tried to install it again on a different terminal and got the same behavior. First tried within [MobaXTerm](https://mobaxterm.mobatek.net/) and then Ubuntu on Windows, standard terminal

## What went wrong?

I got the following output:

```bash
$ curl -sS https://webi.sh/python | sh

Thanks for using webi to install 'python@stable' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers

Cloning into '/home/avilam/.pyenv'...
[...]
Cloning into '/home/avilam/.pyenv/plugins/pyenv-doctor'...
[...]
Cloning into '/home/avilam/.pyenv/plugins/pyenv-installer'...
[...]
Cloning into '/home/avilam/.pyenv/plugins/pyenv-update'...
[...]
Cloning into '/home/avilam/.pyenv/plugins/pyenv-virtualenv'...
[...]
Cloning into '/home/avilam/.pyenv/plugins/pyenv-which-ext'...
[...]
PATH not changed.

PATH not changed.

NOTE: You may also need to CLOSE and RE-OPEN your terminal for pyenv to take effect.
: invalid optionenv/bin/pyenv: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/home/avilam/.pyenv/bin/pyenv: line 3: $'\r': command not found
/home/avilam/.pyenv/bin/pyenv: line 15: syntax error near unexpected token `$'{\r''
'home/avilam/.pyenv/bin/pyenv: line 15: `abort() {
```

Simply running `pyenv` returns the same behavior
```bash
$ pyenv
: invalid optionenv/bin/pyenv: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/home/avilam/.pyenv/bin/pyenv: line 3: $'\r': command not found
/home/avilam/.pyenv/bin/pyenv: line 15: syntax error near unexpected token `$'{\r''
'home/avilam/.pyenv/bin/pyenv: line 15: `abort() {
```

I have this pyenv file:
```bash
$ head /home/avilam/.pyenv/bin/pyenv
#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export PYENV_DEBUG=1
  shift
fi

if [ -n "$PYENV_DEBUG" ]; then
  # https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful
```

## Which OS did you try on?

- [ ] Mac
- [X] Windows on WSL: Ubuntu 18.04
- [X] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

--- 

Let me know how we can further troubleshoot this issue

**Comment by y0rune** [comment] 2022-09-16 09:29
Hello! 
@avila-m-6 can you provide a wsl version and which distro are you using?

Thank you!

**Comment by avila-m-6** [comment] 2022-09-16 14:23
Hi!

I failed to mark Ubuntu 18.04 up there. It's edited now. However, related to WSL, I have an odd behavior, not related to webi.

Sharing to show why I cannot provide wsl version. I am running WSL, because Ubuntu is enabled but I cannot check my wsl version.

![image](https://user-images.githubusercontent.com/75078878/190661059-792e16be-4bcf-42fe-9d3e-9e18ef86fa0a.png)

**Comment by y0rune** [comment] 2022-09-16 19:31
I would like to test it but when I downloaded the Ubuntu Distro into a wsl. The current version is 22.04.1.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/10187235/190714671-5077dc1c-
ec1a-431a-8bd1-6bc16a2a9a34.png">

So I can not reproduce that error. 

As far I see on the store website:
```
When new LTS versions are released, Ubuntu can be upgraded once the first point release is available. This can be done from the command line by using:

sudo do-release-upgrade
```

So I think it is a good opportunity to upgrade the Ubuntu.

**Comment by avila-m-6** [comment] 2022-09-17 01:25
I'll provide an update next week. Interesting this issue could be related to ubuntu version. Thanks for prompt reply

**Comment by coolaj86** [comment] 2022-09-28 07:21
## Python Installer

I was not able to reproduce your issue with the python installer on Ubuntu on Digital Ocean.

I've never heard of MobaXterm and if you were trying to run that on Windows with WSL it may be that it comes with a version of `curl` that swaps out `\n` for `\r\n` to try to make the file "Windows compatible", and the shell you're running (i.e. `zsh`, `bash`, `dash`, or `fish`) may not support Windows-style `\r\n` line endings.

## WSL Issue (unrelated)

It looks like you're trying to run WSL from an Administrator PowerShell rather than a user PowerShell.

You should almost never run PowerShell as Administrator. It messes up the `PATH`.

## Re-open if needed

I'm closing this out because I think the issue you're experiencing is highly specific to your setup. I'm willing to troubleshoot that with you to some degree, but my suspicion is that it's not something that I'll be able to fix by making a change to webi.

**Closed by coolaj86** 2022-09-28 07:21 UTC
Labels: bug

**Comment by y0rune** [comment] 2022-09-28 08:22
Today, I installed the WSL on my windows machine with Ubuntu and that package worked fine. ;)

**Comment by avila-m-6** [comment] 2022-09-28 16:46
Thanks for the troubleshooting. I'll check on my curl, I've been having issues with `/r/n` in other unrelated git issues too. Agree to it being specific to my setup. Thanks for the reply, I'll keep it closed.
